// src/react/spacer/index.tsx
interface Props {
	direction?: "horizontal" | "vertical";
	size: "xs" | "sm" | "md" | "lg";
}

export default function Spacer({ size, direction = "vertical" }: Props) {
	let width = 0;
	let height = 0;
	switch (size) {
		case "xs":
			width = 4;
			height = 4;
			break;
		case "sm":
			width = 8;
			height = 8;
			break;
		case "md":
			width = 16;
			height = 16;
			break;
		case "lg":
			width = 24;
			height = 24;
			break;
	}

	if (direction === "horizontal") {
		return <div style={{ width, height: 0 }}></div>;
	}
	return <div style={{ height, width: 0 }}></div>;
}

// src/svelte/shared/spacer.svelte
<script lang="ts">
	export let direction: "horizontal" | "vertical" = "vertical";
	export let size: "" | "xs" | "sm" | "md" | "lg" = "";

	let width = 0;
	let height = 0;
	switch (size) {
		case "xs":
			if (direction == "horizontal") width = 4;
			if (direction == "vertical") height = 4;
			break;
		case "sm":
			if (direction == "horizontal") width = 8;
			if (direction == "vertical") height = 8;
			break;
		case "md":
			if (direction == "horizontal") width = 16;
			if (direction == "vertical") height = 16;
			break;
		case "lg":
			if (direction == "horizontal") width = 24;
			if (direction == "vertical") height = 24;
			break;
	}
</script>

<div
	style="
		width: {width}px;
		height: {height}px;
	"
></div>
