// src/react/components/properties-filter-app/index.tsx
import React from "react";

import BaseView from "./base-view";
import GroupEditView from "./group-edit-view";

import { PropertyFilterGroup } from "src/types";
import { useAppMount } from "../shared/app-mount-provider";
import EventManager from "src/event/event-manager";
import { generateUUID } from "src/react/services/uuid";

export default function PropertiesFilterApp() {
	const [editMenu, setEditMenu] = React.useState(false);
	const [selectedGroupId, setSelectedGroupId] = React.useState("");
	const [groups, setGroups] = React.useState<PropertyFilterGroup[]>([]);

	const { getCurrentSettings, onSettingsChange } = useAppMount();

	const selectedGroup = groups.find((group) => group.id === selectedGroupId);

	const settings = getCurrentSettings();
	React.useLayoutEffect(() => {
		setSelectedGroupId(settings.filters.properties.selectedGroupId);
		setGroups(settings.filters.properties.groups);
	}, []);

	React.useEffect(() => {
		return () => {
			EventManager.getInstance().emit("properties-filter-update");
		};
	}, []);

	React.useEffect(() => {
		onSettingsChange({
			...settings,
			filters: {
				...settings.filters,
				properties: {
					selectedGroupId,
					groups,
				},
			},
		});
	}, [selectedGroupId, groups]);

	function handleGroupClick(id: string) {
		setSelectedGroupId(id);
	}

	function handleAddPropertyGroupClick() {
		const newGroup: PropertyFilterGroup = {
			id: generateUUID(),
			name: `Group ${groups.length + 1}`,
			filters: [],
			position: groups.length,
			isEnabled: true,
		};

		setSelectedGroupId(newGroup.id);
		setGroups([...groups, newGroup]);
	}

	function handleDeletePropertyGroupClick() {
		const index = groups.findIndex((group) => group.id === selectedGroupId);
		const newGroups = groups.filter(
			(group) => group.id !== selectedGroupId
		);

		let newIndex = index - 1;
		if (newIndex < 0) {
			newIndex = 0;
		}

		setGroups(newGroups);

		if (newGroups.length === 0) {
			setSelectedGroupId("");
		} else {
			setSelectedGroupId(newGroups[newIndex].id);
		}
	}

	function handlePropertyGroupToggle() {
		const newGroups = groups.map((group) =>
			group.id === selectedGroupId
				? { ...group, isEnabled: !group.isEnabled }
				: group
		);

		setGroups(newGroups);
	}

	return (
		<div>
			{editMenu === false && (
				<BaseView
					selectedGroupId={selectedGroupId}
					groups={groups}
					selectedGroup={selectedGroup}
					onEditClick={() => setEditMenu(true)}
					onGroupClick={handleGroupClick}
					onAddPropertyGroupClick={handleAddPropertyGroupClick}
					onDeletePropertyGroupClick={handleDeletePropertyGroupClick}
					onPropertyGroupToggle={handlePropertyGroupToggle}
				/>
			)}
			{editMenu === true && selectedGroup !== undefined && (
				<GroupEditView
					selectedGroup={selectedGroup}
					onBackClick={() => setEditMenu(false)}
					onGroupsChange={setGroups}
				/>
			)}
		</div>
	);
}

// src/svelte/properties-filter-app/index.svelte
<script lang="ts">
	import EventManager from "src/event/event-manager";
	import { onMount } from "svelte";
	import store from "../shared/services/store";
	import VaultExplorerPlugin from "src/main";
	import { PropertyFilterGroup } from "src/types";
	import { generateUUID } from "../shared/services/uuid";
	import BaseView from "./components/base-view.svelte";
	import GroupEditView from "./components/group-edit-view.svelte";

	let editMenu: boolean = false;
	let selectedGroupId: string = "";
	let groups: PropertyFilterGroup[] = [];
	let plugin: VaultExplorerPlugin;

	$: selectedGroup = groups.find((group) => group.id === selectedGroupId);

	$: groups, saveSettings();

	async function saveSettings() {
		plugin.settings.filters.properties.groups = groups;
		await plugin.saveSettings();
	}

	store.plugin.subscribe((p) => {
		plugin = p;

		groups = plugin.settings.filters.properties.groups;
		selectedGroupId = groups.length > 0 ? groups[0].id : "";
	});

	onMount(() => {
		return () => {
			EventManager.getInstance().emit("properties-filter-update");
		};
	});

	function handleGroupClick(e: CustomEvent) {
		const { id } = e.detail;
		selectedGroupId = id;
	}

	function handleAddGroupClick() {
		const newGroup: PropertyFilterGroup = {
			id: generateUUID(),
			name: `Group ${groups.length + 1}`,
			filters: [],
			position: groups.length,
			isEnabled: true,
		};

		selectedGroupId = newGroup.id;
		groups = [...groups, newGroup];
	}

	function handleDeleteGroupClick() {
		const index = groups.findIndex((group) => group.id === selectedGroupId);
		const newGroups = groups.filter(
			(group) => group.id !== selectedGroupId,
		);

		let newIndex = index - 1;
		if (newIndex < 0) {
			newIndex = 0;
		}

		groups = newGroups;

		if (newGroups.length === 0) {
			selectedGroupId = "";
		} else {
			selectedGroupId = newGroups[newIndex].id;
		}
	}

	function handleFilterAddClick(e: CustomEvent) {
		const { filter } = e.detail;

		const newGroups = groups.map((group) =>
			group.id === selectedGroupId
				? { ...group, filters: [...group.filters, filter] }
				: group,
		);

		groups = newGroups;
	}

	function handleGroupNameChange(e: CustomEvent) {
		const { name } = e.detail;

		const newGroups = groups.map((group) =>
			group.id === selectedGroupId ? { ...group, name } : group,
		);

		groups = newGroups;
	}

	function handleGroupToggle() {
		const newGroups = groups.map((group) =>
			group.id === selectedGroupId
				? { ...group, isEnabled: !group.isEnabled }
				: group,
		);

		groups = newGroups;
	}

	function handleFilterConditionChange(e: CustomEvent) {
		const { id, condition } = e.detail;

		console.log(id, condition);

		const newGroups = groups.map((group) =>
			group.id === selectedGroupId
				? {
						...group,
						filters: group.filters.map((filter) =>
							filter.id === id
								? { ...filter, condition }
								: filter,
						),
					}
				: group,
		);

		groups = newGroups;
	}

	function handleFilterDeleteClick(e: CustomEvent) {
		const { id } = e.detail;

		const newGroups = groups.map((group) =>
			group.id === selectedGroupId
				? {
						...group,
						filters: group.filters.filter(
							(filter) => filter.id !== id,
						),
					}
				: group,
		);

		groups = newGroups;
	}

	function handleFilterNameChange(e: CustomEvent) {
		const { id, name } = e.detail;

		const newGroups = groups.map((group) =>
			group.id === selectedGroupId
				? {
						...group,
						filters: group.filters.map((filter) =>
							filter.id === id
								? { ...filter, propertyName: name }
								: filter,
						),
					}
				: group,
		);

		groups = newGroups;
	}

	function handleFilterToggle(e: CustomEvent) {
		const { id } = e.detail;

		const newGroups = groups.map((group) =>
			group.id === selectedGroupId
				? {
						...group,
						filters: group.filters.map((filter) =>
							filter.id === id
								? { ...filter, isEnabled: !filter.isEnabled }
								: filter,
						),
					}
				: group,
		);

		groups = newGroups;
	}

	function handleFilterValueChange(e: CustomEvent) {
		const { id, value } = e.detail;

		const newGroups = groups.map((group) =>
			group.id === selectedGroupId
				? {
						...group,
						filters: group.filters.map((filter) =>
							filter.id === id ? { ...filter, value } : filter,
						),
					}
				: group,
		);

		groups = newGroups;
	}
</script>

<div>
	{#if editMenu === false}
		<BaseView
			{groups}
			{selectedGroup}
			on:editClick={() => (editMenu = true)}
			on:groupClick={handleGroupClick}
			on:addGroupClick={handleAddGroupClick}
			on:deleteGroupClick={handleDeleteGroupClick}
			on:groupToggle={handleGroupToggle}
			on:groupNameChange={handleGroupNameChange}
			on:filterAddClick={handleFilterAddClick}
			on:groupClick={handleGroupClick}
			on:filterConditionChange={handleFilterConditionChange}
			on:filterDeleteClick={handleFilterDeleteClick}
			on:filterNameChange={handleFilterNameChange}
			on:filterToggle={handleFilterToggle}
			on:filterValueChange={handleFilterValueChange}
		/>
	{/if}
	{#if editMenu === true && selectedGroup !== undefined}
		<GroupEditView
			{selectedGroup}
			on:backClick={() => (editMenu = false)}
			on:groupNameChange={handleGroupNameChange}
			on:filterAddClick={handleFilterAddClick}
			on:groupClick={handleGroupClick}
			on:filterConditionChange={handleFilterConditionChange}
			on:filterDeleteClick={handleFilterDeleteClick}
			on:filterNameChange={handleFilterNameChange}
			on:filterToggle={handleFilterToggle}
			on:filterValueChange={handleFilterValueChange}
		/>
	{/if}
</div>
