// src/react/flex/index.tsx
interface Props {
	direction?: "row" | "column" | "row-reverse" | "column-reverse";
	justify?: "flex-start" | "center" | "space-between" | "flex-end";
	align?: "flex-start" | "center" | "flex-end";
	wrap?: "wrap" | "nowrap";
	width?: string;
	height?: string;
	children: React.ReactNode;
}

export default function Flex({
	direction = "row",
	justify = "flex-start",
	align = "flex-start",
	wrap = "wrap",
	width,
	height,
	children,
}: Props) {
	if (width === undefined && direction === "row") {
		width = "100%";
	} else if (height === undefined && direction === "column") {
		height = "100%";
	}
	return (
		<div
			className="frontmatter-view-flex"
			style={{
				display: "flex",
				flexDirection: direction,
				justifyContent: justify,
				alignItems: align,
				flexWrap: wrap,
				width,
				height,
			}}
		>
			{children}
		</div>
	);
}

// src/svelte/shared/components/flex.svelte
<script lang="ts">
	export let direction: "row" | "column" = "row";
	export let justify: "flex-start" | "center" | "space-between" | "flex-end" =
		"flex-start";
	export let align: "flex-start" | "center" | "flex-end" = "flex-start";
	export let wrap: "wrap" | "nowrap" = "nowrap";
	export let width: string = "";
	export let height: string = "";

	if (width === undefined && direction === "row") {
		width = "100%";
	} else if (height === undefined && direction === "column") {
		height = "100%";
	}
</script>

<div
	class="vault-explorer-flex"
	style="
		display: flex;
		flex-direction: {direction};
		justify-content: {justify};
		align-items: {align};
		flex-wrap: {wrap};
		width: {width};
		height: {height};
	"
>
	<slot />
</div>
