// src/react/spacer/index.tsx
interface Props {
	direction?: "horizontal" | "vertical";
	size: "xs" | "sm" | "md" | "lg";
}

export default function Spacer({ size, direction = "vertical" }: Props) {
	let width = 0;
	let height = 0;
	switch (size) {
		case "xs":
			width = 4;
			height = 4;
			break;
		case "sm":
			width = 8;
			height = 8;
			break;
		case "md":
			width = 16;
			height = 16;
			break;
		case "lg":
			width = 24;
			height = 24;
			break;
	}

	if (direction === "horizontal") {
		return <div style={{ width, height: 0 }}></div>;
	}
	return <div style={{ height, width: 0 }}></div>;
}

// src/svelte/shared/components/spacer.svelte
<script lang="ts">
	export let direction: "horizontal" | "vertical" = "horizontal";
	export let size: "" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" = "";

	$: size, direction, findDimesions();

	let width = 0;
	let height = 0;

	function findDimesions() {
		switch (size) {
			case "xs":
				if (direction == "horizontal") width = 4;
				if (direction == "vertical") height = 4;
				break;
			case "sm":
				if (direction == "horizontal") width = 8;
				if (direction == "vertical") height = 8;
				break;
			case "md":
				if (direction == "horizontal") width = 16;
				if (direction == "vertical") height = 16;
				break;
			case "lg":
				if (direction == "horizontal") width = 24;
				if (direction == "vertical") height = 24;
				break;
			case "xl":
				if (direction == "horizontal") width = 32;
				if (direction == "vertical") height = 32;
				break;
			case "2xl":
				if (direction == "horizontal") width = 48;
				if (direction == "vertical") height = 48;
				break;
		}
	}
</script>

<div
	style="
		width: {width}px;
		height: {height}px;
	"
></div>
