// src/react/stack/index.tsx
interface Props {
	spacing?: "xs" | "sm" | "md" | "lg" | "xl";
	justify?: "flex-start" | "center" | "space-between" | "flex-end";
	align?: "flex-start" | "center" | "flex-end";
	direction?: "row" | "column";
	width?: string;
	height?: string;
	children: React.ReactNode;
}

export default function Stack({
	direction = "row",
	spacing = "md",
	justify,
	align,
	children,
	width,
	height,
}: Props) {
	let spacingPx = 0;
	if (spacing === "xs") {
		spacingPx = 4;
	} else if (spacing === "sm") {
		spacingPx = 8;
	} else if (spacing === "md") {
		spacingPx = 16;
	} else if (spacing === "lg") {
		spacingPx = 24;
	} else if (spacing === "xl") {
		spacingPx = 32;
	}
	return (
		<div
			className="vault-explorer-stack"
			style={{
				display: "flex",
				flexDirection: direction,
				justifyContent: justify,
				alignItems: align,
				[direction === "row" ? "columnGap" : "rowGap"]: spacingPx,
				width,
				height,
			}}
		>
			{children}
		</div>
	);
}

// src/svelte/shared/components/stack.svelte
<script lang="ts">
	export let spacing: "xs" | "sm" | "md" | "lg" | "xl" = "md";
	export let justify:
		| "flex-start"
		| "center"
		| "space-between"
		| "flex-end"
		| "unset" = "unset";
	export let align: "flex-start" | "center" | "flex-end" | "unset" = "unset";
	export let direction: "row" | "column" | "row-reverse" | "column-reverse" =
		"row";
	export let width = "unset";
	export let height = "unset";

	let spacingPx = 0;
	switch (spacing) {
		case "xs":
			spacingPx = 4;
			break;
		case "sm":
			spacingPx = 8;
			break;
		case "md":
			spacingPx = 16;
			break;
		case "lg":
			spacingPx = 24;
			break;
		case "xl":
			spacingPx = 32;
			break;
	}
</script>

<div
	class="vault-explorer-stack"
	style="
		display: flex;
		flex-direction: {direction};
		justify-content: {justify};
		align-items: {align};
		{direction === 'row' || direction === 'row-reverse'
		? 'column-gap'
		: 'row-gap'}: {spacingPx}px;
		width: {width};
		height: {height};
	"
>
	<slot />
</div>
