// src/react/components/properties-filter-app/group-edit-view/index.tsx
import {
	PropertyFilterGroup,
	TextFilterCondition,
	TextPropertyFilter,
} from "src/types";
import IconButton from "../../shared/icon-button";
import Stack from "../../shared/stack";
import Divider from "../../shared/divider";
import PropertyFilterList from "../property-filter-list";
import { generateUUID } from "src/react/services/uuid";

interface Props {
	selectedGroup: PropertyFilterGroup;
	onBackClick: () => void;
	onGroupsChange: React.Dispatch<React.SetStateAction<PropertyFilterGroup[]>>;
}

export default function GroupEditView({
	selectedGroup,
	onBackClick,
	onGroupsChange,
}: Props) {
	function handleAddPropertyClick() {
		const newFilter: TextPropertyFilter = {
			id: generateUUID(),
			propertyName: "",
			operator: "and",
			isEnabled: true,
			condition: TextFilterCondition.IS,
			value: "",
		};

		onGroupsChange((groups) =>
			groups.map((group) =>
				group.id === selectedGroup.id
					? { ...group, filters: [...group.filters, newFilter] }
					: group
			)
		);
	}

	function handleGroupNameChange(name: string) {
		onGroupsChange((groups) =>
			groups.map((group) =>
				group.id === selectedGroup.id ? { ...group, name } : group
			)
		);
	}

	return (
		<Stack direction="column" align="flex-start" spacing="sm">
			<Stack spacing="sm">
				<IconButton
					ariaLabel="Back"
					iconId="arrow-left"
					onClick={onBackClick}
				/>
				<input
					type="text"
					value={selectedGroup.name}
					onChange={(e) => handleGroupNameChange(e.target.value)}
				/>
			</Stack>
			<Divider />
			<PropertyFilterList
				selectedGroup={selectedGroup}
				onGroupsChange={onGroupsChange}
			/>
			<IconButton
				ariaLabel="Add filter"
				iconId="plus"
				onClick={handleAddPropertyClick}
			/>
		</Stack>
	);
}

// src/svelte/custom-filter-app/components/group-edit-view.svelte
<script lang="ts">
	import Divider from "src/svelte/shared/components/divider.svelte";
	import IconButton from "src/svelte/shared/components/icon-button.svelte";
	import Stack from "src/svelte/shared/components/stack.svelte";

	import { TFilterGroup } from "src/types";
	import FilterRuleList from "./filter-rule-list.svelte";

	import { createEventDispatcher } from "svelte";
	import { createPropertyFilter } from "../services/utils";
	import Spacer from "src/svelte/shared/components/spacer.svelte";
	const dispatch = createEventDispatcher();

	export let selectedGroup: TFilterGroup;

	function handleFilterAddClick() {
		const newFilter = createPropertyFilter();
		dispatch("ruleAddClick", { filter: newFilter });
	}

	function handleGroupNameChange(e: Event) {
		const name = (e.target as HTMLInputElement).value;
		dispatch("groupNameChange", { name });
	}
</script>

<Stack width="100%" direction="column" align="flex-start" spacing="sm">
	<div class="vault-explorer-group-edit-view__header">
		<input
			type="text"
			value={selectedGroup.name}
			on:change={handleGroupNameChange}
		/>
	</div>
	<Divider borderWidth="1px" />
	<div class="vault-explorer-group-edit-view__body">
		{#if selectedGroup.rules.length > 0}
			<FilterRuleList
				rules={selectedGroup.rules}
				on:ruleTypeChange
				on:ruleConditionChange
				on:ruleOperatorChange
				on:ruleValueChange
				on:ruleValueChange
				on:ruleToggle
				on:ruleDeleteClick
				on:ruleDuplicateClick
				on:propertyTypeChange
				on:propertyNameChange
				on:propertyMatchWhenPropertyDNEChange
				on:propertyValueDataChange
				on:folderSubfoldersToggle
			/>
			<Spacer direction="vertical" size="sm" />
		{/if}
		<IconButton
			ariaLabel="Add filter rule"
			iconId="plus"
			on:click={handleFilterAddClick}
		/>
	</div>
</Stack>

<style>
	.vault-explorer-group-edit-view__header {
		padding: 5px 10px;
	}

	.vault-explorer-group-edit-view__body {
		padding: 5px 10px;
		overflow-y: auto;
		max-height: 200px;
	}
</style>
