// src/svelte/app/index.svelte
<script lang="ts">
	import Stack from "../shared/stack.svelte";
	import Flex from "../shared/flex.svelte";
	import IconButton from "../shared/icon-button.svelte";
	import Checkbox from "../shared/checkbox.svelte";
	import TabList from "../shared/tab-list.svelte";
	import Tab from "../shared/tab.svelte";
	import { Menu, TFile, TFolder } from "obsidian";
	import PropertiesFilterModal from "src/obsidian/properties-filter-modal";
	import { CurrentView, SortFilter, TimestampFilter } from "src/types";
	import store from "./store";
	import VaultExplorerPlugin from "src/main";
	import GridView from "./components/grid-view.svelte";
	import ListView from "./components/list-view.svelte";
	import { favoriteFilter } from "./services/filters/favorite-filter";
	import { filterByFolder } from "./services/filters/folder-filter";
	import { filterBySearch } from "./services/filters/search-filter";
	import { filterByTimestamp } from "./services/filters/timestamp-filter";
	import { filterByProperty } from "./services/filters/property-filter";
	import { formatFileDataForRender } from "./services/render-utils";
	import {
		getMidnightToday,
		getMidnightThisWeek,
		getMidnightLastWeek,
	} from "./services/time-utils";
	import _ from "lodash";

	let plugin: VaultExplorerPlugin;

	//TODO move to store
	const midnightToday = getMidnightToday();
	const midnightThisWeek = getMidnightThisWeek();
	const midnightLastWeek = getMidnightLastWeek();

	let folders: string[] = [];

	let searchFilter: string = "";
	let folderPath: string = "/";
	let sortFilter: SortFilter = "file-name-asc";
	let timestampFilter: TimestampFilter = "all";
	let onlyFavorites: boolean = false;
	let currentView: CurrentView = "grid";

	let markdownFiles: TFile[] = [];

	const debounceSearchFilter = _.debounce((e) => {
		searchFilter = e.target.value;
	}, 300);

	const debounceFavoriteFilter = _.debounce((value) => {
		onlyFavorites = value;
	}, 300);

	$: sorted = [...markdownFiles].sort((a, b) => {
		if (sortFilter === "file-name-asc") {
			return a.name.toLowerCase().localeCompare(b.name.toLowerCase());
		} else if (sortFilter === "file-name-desc") {
			return b.name.toLowerCase().localeCompare(a.name.toLowerCase());
		} else if (sortFilter === "modified-asc") {
			return a.stat.mtime - b.stat.mtime;
		} else if (sortFilter === "modified-desc") {
			return b.stat.mtime - a.stat.mtime;
		}
		return 0;
	});

	//TODO update values every minute
	$: filteredTimestamp = sorted.filter((file) =>
		filterByTimestamp(file, timestampFilter, {
			midnightToday,
			midnightThisWeek,
			midnightLastWeek,
		}),
	);

	$: filteredProperty = filteredTimestamp.filter((file) =>
		filterByProperty(
			plugin.app,
			file,
			plugin.settings.filters.properties.groups,
		),
	);

	$: filteredFolder = filteredProperty.filter((file) =>
		filterByFolder(file, folderPath),
	);

	$: formatted = filteredFolder.map((file) =>
		formatFileDataForRender(plugin.app, plugin.settings, file),
	);

	$: filterSearch = formatted.filter((file) =>
		filterBySearch(file, searchFilter),
	);

	$: renderData = filterSearch.filter((file) =>
		favoriteFilter(file, onlyFavorites),
	);

	store.plugin.subscribe((p) => {
		plugin = p;

		const allFiles = plugin.app.vault.getAllLoadedFiles();
		folders = allFiles
			.filter((file) => file instanceof TFolder)
			.map((folder) => folder.path);

		markdownFiles = plugin.app.vault.getMarkdownFiles();
	});

	$: searchFilter,
		folderPath,
		sortFilter,
		timestampFilter,
		onlyFavorites,
		currentView,
		saveSettings();

	async function saveSettings() {
		console.log("updateSettings");
		plugin.settings.filters.search = searchFilter;
		plugin.settings.filters.folder = folderPath;
		plugin.settings.filters.sort = sortFilter;
		plugin.settings.filters.timestamp = timestampFilter;
		plugin.settings.filters.onlyFavorites = onlyFavorites;
		plugin.settings.currentView = currentView;
		await plugin.saveSettings();
	}

	function openPropertiesFilterModal() {
		new PropertiesFilterModal(plugin).open();
	}

	function openSortMenu(e: CustomEvent) {
		const nativeEvent = e.detail.nativeEvent as MouseEvent;
		const menu = new Menu();
		menu.setUseNativeMenu(true);
		menu.addItem((item) => {
			item.setTitle("File name (A-Z)");
			item.setChecked(sortFilter === "file-name-asc");
			item.onClick(() => (sortFilter = "file-name-asc"));
		});
		menu.addItem((item) => {
			item.setTitle("File name (Z-A)");
			item.setChecked(sortFilter === "file-name-desc");
			item.onClick(() => (sortFilter = "file-name-desc"));
		});
		menu.addSeparator();
		menu.addItem((item) => {
			item.setTitle("Modified time (new to old)");
			item.setChecked(sortFilter === "modified-desc");
			item.onClick(() => (sortFilter = "modified-desc"));
		});
		menu.addItem((item) => {
			item.setTitle("Modified time (old to new)");
			item.setChecked(sortFilter === "modified-asc");
			item.onClick(() => (sortFilter = "modified-asc"));
		});
		menu.showAtMouseEvent(nativeEvent);
	}

	function openFolderFilterMenu(e: CustomEvent) {
		const nativeEvent = e.detail.nativeEvent as MouseEvent;

		const menu = new Menu();
		menu.setUseNativeMenu(true);

		for (const folder of folders) {
			menu.addItem((item) => {
				item.setTitle(folder === "/" ? "All" : folder);
				item.setChecked(folderPath === folder);
				item.onClick(() => (folderPath = folder));
			});
		}

		menu.showAtMouseEvent(nativeEvent);
	}

	function openListFilterMenu(e: CustomEvent) {
		const nativeEvent = e.detail.nativeEvent as MouseEvent;

		const menu = new Menu();
		menu.setUseNativeMenu(true);
		menu.addItem((item) => {
			item.setTitle("All");
			item.setChecked(timestampFilter === "all");
			item.onClick(() => (timestampFilter = "all"));
		});
		menu.addSeparator();
		menu.addItem((item) => {
			item.setTitle("Modified today");
			item.setChecked(timestampFilter === "modified-today");
			item.onClick(() => (timestampFilter = "modified-today"));
		});
		menu.addItem((item) => {
			item.setTitle("Created today");
			item.setChecked(timestampFilter === "created-today");
			item.onClick(() => (timestampFilter = "created-today"));
		});
		menu.addSeparator();
		menu.addItem((item) => {
			item.setTitle("Modifed this week");
			item.setChecked(timestampFilter === "modified-this-week");
			item.onClick(() => (timestampFilter = "modified-this-week"));
		});
		menu.addItem((item) => {
			item.setTitle("Created this week");
			item.setChecked(timestampFilter === "created-this-week");
			item.onClick(() => (timestampFilter = "created-this-week"));
		});
		menu.addSeparator();
		menu.addItem((item) => {
			item.setTitle("Modifed 2 weeks");
			item.setChecked(timestampFilter === "modified-2-weeks");
			item.onClick(() => (timestampFilter = "modified-2-weeks"));
		});
		menu.addItem((item) => {
			item.setTitle("Created 2 weeks");
			item.setChecked(timestampFilter === "created-2-weeks");
			item.onClick(() => (timestampFilter = "created-2-weeks"));
		});

		menu.showAtMouseEvent(nativeEvent);
	}

	function handleOnlyFavoritesChange(e: CustomEvent) {
		const nativeEvent = e.detail.nativeEvent;
		const value = (nativeEvent.target as HTMLInputElement).checked;
		debounceFavoriteFilter(value);
	}

	let currentPage = 1;
	const pageSize = 50;
	$: totalItems = renderData.length;
	$: totalPages = Math.ceil(totalItems / pageSize);

	function changePage(newPage: number) {
		currentPage = newPage;
	}
</script>

<div class="vault-explorer">
	<div class="vault-explorer-header">
		<Stack spacing="md">
			<input
				type="text"
				placeholder="Search..."
				value={searchFilter}
				on:input={debounceSearchFilter}
			/>
		</Stack>
		<Flex justify="space-between">
			<Stack spacing="sm">
				<Checkbox
					id="favorites"
					label="Favorites"
					value={onlyFavorites}
					on:change={handleOnlyFavoritesChange}
				/>
				<Flex>
					<IconButton
						ariaLabel="Change folder filter"
						iconId="folder"
						on:click={openFolderFilterMenu}
					/>
					<IconButton
						ariaLabel="Change timestamp filter"
						iconId="clock"
						on:click={openListFilterMenu}
					/>
					<IconButton
						ariaLabel="Change properties filter"
						iconId="sliders-horizontal"
						on:click={openPropertiesFilterModal}
					/>
					<IconButton
						ariaLabel="Change sort order"
						iconId="arrow-up-narrow-wide"
						on:click={openSortMenu}
					/>
				</Flex>
			</Stack>
			<Stack justify="flex-end" align="center">
				<Flex>
					<IconButton
						iconId="chevrons-left"
						ariaLabel="First page"
						on:click={() => changePage(1)}
					/>
					<IconButton
						iconId="chevron-left"
						ariaLabel="Previous page"
						disabled={currentPage === 1}
						on:click={() => changePage(currentPage - 1)}
					/>
					<IconButton
						iconId="chevron-right"
						ariaLabel="Next page"
						disabled={currentPage === totalPages}
						on:click={() => changePage(currentPage + 1)}
					/>
					<IconButton
						iconId="chevrons-right"
						ariaLabel="Last page"
						on:click={() => changePage(totalPages)}
					/>
				</Flex>
				{currentPage} / {totalPages}
			</Stack>
		</Flex>
		<Stack spacing="sm">
			<TabList>
				<Tab on:click={() => (currentView = "grid")}>Grid</Tab>
				<Tab on:click={() => (currentView = "list")}>List</Tab>
			</TabList>
		</Stack>
		{#if currentView === "grid"}
			<GridView data={renderData} {currentPage} {pageSize} />
		{:else}
			<ListView data={renderData} {currentPage} {pageSize} />
		{/if}
	</div>
</div>

<style>
	.vault-explorer {
		display: flex;
		flex-direction: column;
	}

	.vault-explorer-header {
		display: flex;
		flex-direction: column;
		row-gap: 1rem;
		margin-bottom: 2rem;
	}

	.vault-explorer input[type="text"] {
		width: 100%;
		max-width: 300px;
	}
</style>

// src/react/components/app/index.tsx
export {};

// import { Menu, TFile, TFolder } from "obsidian";

// import React from "react";

// import { useAppMount } from "../shared/app-mount-provider";
// import Checkbox from "../shared/checkbox";
// import Flex from "../shared/flex";
// import Stack from "../shared/stack";
// import GridView from "./grid-view";
// import ListView from "./list-view";
// import Tab from "../shared/tab";
// import TabList from "../shared/tab-list";
// import IconButton from "../shared/icon-button";

// import EventManager from "src/event/event-manager";
// import { MarkdownFileRenderData } from "./types";
// import { CurrentView, SortFilter, TimestampFilter } from "src/types";

// import PropertiesFilterModal from "src/obsidian/properties-filter-modal";

// import "./styles.css";
// import { filterByTimestamp } from "./services/filters/timestamp-filter";
// import { filterByProperty } from "./services/filters/property-filter";
// import { filterByFolder } from "./services/filters/folder-filter";
// import { favoriteFilter as filterByFavorite } from "./services/filters/favorite-filter";
// import { filterBySearch } from "./services/filters/search-filter";
// import { formatFileDataForRender } from "./services/render-utils";
// import {
// 	getMidnightLastWeek,
// 	getMidnightThisWeek,
// 	getMidnightToday,
// } from "./services/time-utils";

// const midnightToday = getMidnightToday();
// const midnightThisWeek = getMidnightThisWeek();
// const midnightLastWeek = getMidnightLastWeek();

// export default function ReactApp() {
// 	const [folderPath, setFolderPath] = React.useState<string>("/");
// 	const [searchFilter, setSearch] = React.useState<string>("");
// 	const [onlyFavorites, setOnlyFavorites] = React.useState<boolean>(false);
// 	const [timestampFilter, setTimestampFilter] =
// 		React.useState<TimestampFilter>("all");
// 	const [currentView, setCurrentView] = React.useState<CurrentView>("grid");
// 	const [sortFilter, setSortFilter] =
// 		React.useState<SortFilter>("file-name-asc");

// 	const { app, getCurrentSettings, onSettingsChange } = useAppMount();
// 	const settings = getCurrentSettings();

// 	React.useLayoutEffect(() => {
// 		setFolderPath(settings.filters.folder);
// 		setSearch(settings.filters.search);
// 		setOnlyFavorites(settings.filters.onlyFavorites);
// 		setCurrentView(settings.currentView);
// 		setTimestampFilter(settings.filters.timestamp);
// 		setSortFilter(settings.filters.sort);
// 	}, []);

// 	const [refreshTime, setRefreshTime] = React.useState(0);

// 	//TODO optimize
// 	React.useEffect(() => {
// 		const handlePropertiesFilterUpdate = () => {
// 			setRefreshTime(Date.now());
// 		};

// 		EventManager.getInstance().on(
// 			"properties-filter-update",
// 			handlePropertiesFilterUpdate
// 		);

// 		return () => {
// 			EventManager.getInstance().emit("properties-filter-update");
// 		};
// 	}, []);

// 	//TODO optimize
// 	React.useEffect(() => {
// 		const handleRenameFile = (oldPath: string, newPath: string) => {
// 			setRefreshTime(Date.now());
// 		};

// 		EventManager.getInstance().on("rename-file", handleRenameFile);
// 		return () => {
// 			EventManager.getInstance().off("rename-file", handleRenameFile);
// 		};
// 	}, []);

// 	//TODO optimize
// 	React.useEffect(() => {
// 		const handleCreateFile = (oldPath: string, newPath: string) => {
// 			setRefreshTime(Date.now());
// 		};

// 		EventManager.getInstance().on("create-file", handleCreateFile);
// 		return () => {
// 			EventManager.getInstance().off("create-file", handleCreateFile);
// 		};
// 	}, []);

// 	//TODO optimize
// 	React.useEffect(() => {
// 		const handleDeleteFile = (oldPath: string, newPath: string) => {
// 			setRefreshTime(Date.now());
// 		};

// 		EventManager.getInstance().on("delete-file", handleDeleteFile);
// 		return () => {
// 			EventManager.getInstance().off("delete-file", handleDeleteFile);
// 		};
// 	}, []);

// 	//TODO optimize
// 	React.useEffect(() => {
// 		const handleModifyFile = (oldPath: string, newPath: string) => {
// 			setRefreshTime(Date.now());
// 		};

// 		EventManager.getInstance().on("modify-file", handleModifyFile);
// 		return () => {
// 			EventManager.getInstance().off("modify-file", handleModifyFile);
// 		};
// 	}, []);

// 	//TODO optimize
// 	React.useEffect(() => {
// 		const handleMetadataChange = (filePath: string) => {
// 			setRefreshTime(Date.now());
// 		};

// 		EventManager.getInstance().on("metadata-change", handleMetadataChange);
// 		return () => {
// 			EventManager.getInstance().off(
// 				"metadata-change",
// 				handleMetadataChange
// 			);
// 		};
// 	}, []);

// 	React.useEffect(() => {
// 		onSettingsChange({
// 			...settings,
// 			filters: {
// 				folder: folderPath,
// 				search: searchFilter,
// 				onlyFavorites,
// 				timestamp: timestampFilter,
// 				sort: sortFilter,
// 				properties: { ...settings.filters.properties },
// 			},
// 			currentView: currentView,
// 		});
// 	}, [
// 		onSettingsChange,
// 		sortFilter,
// 		folderPath,
// 		searchFilter,
// 		onlyFavorites,
// 		timestampFilter,
// 		currentView,
// 	]);

// 	function openPropertiesFilterModal() {
// 		new PropertiesFilterModal(
// 			app,
// 			getCurrentSettings,
// 			onSettingsChange
// 		).open();
// 	}

// 	function openSortMenu(e: React.MouseEvent) {
// 		const menu = new Menu();
// 		menu.setUseNativeMenu(true);
// 		menu.addItem((item) => {
// 			item.setTitle("File name (A-Z)");
// 			item.setChecked(sortFilter === "file-name-asc");
// 			item.onClick(() => setSortFilter("file-name-asc"));
// 		});
// 		menu.addItem((item) => {
// 			item.setTitle("File name (Z-A)");
// 			item.setChecked(sortFilter === "file-name-desc");
// 			item.onClick(() => setSortFilter("file-name-desc"));
// 		});
// 		menu.addSeparator();
// 		menu.addItem((item) => {
// 			item.setTitle("Modified time (new to old)");
// 			item.setChecked(sortFilter === "modified-desc");
// 			item.onClick(() => setSortFilter("modified-desc"));
// 		});
// 		menu.addItem((item) => {
// 			item.setTitle("Modified time (old to new)");
// 			item.setChecked(sortFilter === "modified-asc");
// 			item.onClick(() => setSortFilter("modified-asc"));
// 		});
// 		menu.showAtMouseEvent(e.nativeEvent);
// 	}

// 	function openFolderFilterMenu(e: React.MouseEvent) {
// 		const menu = new Menu();
// 		menu.setUseNativeMenu(true);

// 		for (const folder of folders) {
// 			menu.addItem((item) => {
// 				item.setTitle(folder === "/" ? "All" : folder);
// 				item.setChecked(folderPath === folder);
// 				item.onClick(() => setFolderPath(folder));
// 			});
// 		}

// 		menu.showAtMouseEvent(e.nativeEvent);
// 	}

// 	function openListFilterMenu(e: React.MouseEvent) {
// 		const menu = new Menu();
// 		menu.setUseNativeMenu(true);
// 		menu.addItem((item) => {
// 			item.setTitle("All");
// 			item.setChecked(timestampFilter === "all");
// 			item.onClick(() => setTimestampFilter("all"));
// 		});
// 		menu.addSeparator();
// 		menu.addItem((item) => {
// 			item.setTitle("Modified today");
// 			item.setChecked(timestampFilter === "modified-today");
// 			item.onClick(() => setTimestampFilter("modified-today"));
// 		});
// 		menu.addItem((item) => {
// 			item.setTitle("Created today");
// 			item.setChecked(timestampFilter === "created-today");
// 			item.onClick(() => setTimestampFilter("created-today"));
// 		});
// 		menu.addSeparator();
// 		menu.addItem((item) => {
// 			item.setTitle("Modifed this week");
// 			item.setChecked(timestampFilter === "modified-this-week");
// 			item.onClick(() => setTimestampFilter("modified-this-week"));
// 		});
// 		menu.addItem((item) => {
// 			item.setTitle("Created this week");
// 			item.setChecked(timestampFilter === "created-this-week");
// 			item.onClick(() => setTimestampFilter("created-this-week"));
// 		});
// 		menu.addSeparator();
// 		menu.addItem((item) => {
// 			item.setTitle("Modifed 2 weeks");
// 			item.setChecked(timestampFilter === "modified-2-weeks");
// 			item.onClick(() => setTimestampFilter("modified-2-weeks"));
// 		});
// 		menu.addItem((item) => {
// 			item.setTitle("Created 2 weeks");
// 			item.setChecked(timestampFilter === "created-2-weeks");
// 			item.onClick(() => setTimestampFilter("created-2-weeks"));
// 		});

// 		menu.showAtMouseEvent(e.nativeEvent);
// 	}

// 	//TODO update for folder
// 	const allFiles = React.useMemo(() => {
// 		return app.vault.getAllLoadedFiles();
// 	}, [refreshTime]);

// 	const folders = allFiles
// 		.filter((file) => file instanceof TFolder)
// 		.map((folder) => folder.path);

// 	const folderFiles = app.vault
// 		.getMarkdownFiles()
// 		.filter((file) => file instanceof TFile)
// 		.filter((file) => {
// 			if (folderPath === "") {
// 				return true;
// 			} else if (folderPath === "/") {
// 				return true;
// 			}
// 			return file.path.startsWith(folderPath ?? "/");
// 		});

// 	const sortedMarkdownFiles = React.useMemo(
// 		() =>
// 			[...app.vault.getMarkdownFiles()].sort((a, b) => {
// 				if (sortFilter === "file-name-asc") {
// 					return a.name
// 						.toLowerCase()
// 						.localeCompare(b.name.toLowerCase());
// 				} else if (sortFilter === "file-name-desc") {
// 					return b.name
// 						.toLowerCase()
// 						.localeCompare(a.name.toLowerCase());
// 				} else if (sortFilter === "modified-asc") {
// 					return a.stat.mtime - b.stat.mtime;
// 				} else if (sortFilter === "modified-desc") {
// 					return b.stat.mtime - a.stat.mtime;
// 				}
// 				return 0;
// 			}),
// 		[refreshTime]
// 	);

// 	let filteredData: TFile[] = sortedMarkdownFiles;
// 	//TODO update every minute
// 	filteredData = filteredData.filter((file) =>
// 		filterByTimestamp(file, timestampFilter, {
// 			midnightToday,
// 			midnightThisWeek,
// 			midnightLastWeek,
// 		})
// 	);
// 	filteredData = filteredData.filter((file) =>
// 		filterByProperty(app, file, settings.filters.properties.groups)
// 	);
// 	filteredData = filteredData.filter((file) =>
// 		filterByFolder(file, folderPath)
// 	);

// 	let renderData = filteredData.map((file) =>
// 		formatFileDataForRender(app, settings, file)
// 	);
// 	renderData = renderData.filter((file) =>
// 		filterBySearch(file, searchFilter)
// 	);
// 	renderData = renderData.filter((file) =>
// 		filterByFavorite(file, onlyFavorites)
// 	);

// 	return (
// 		<div className="vault-explorer">
// 			<div className="vault-explorer-header">
// 				<Stack spacing="md">
// 					<input
// 						type="text"
// 						placeholder="Search..."
// 						value={searchFilter}
// 						onChange={(e) => setSearch(e.target.value)}
// 					/>
// 				</Stack>
// 				<Flex justify="space-between">
// 					<Stack spacing="sm">
// 						<Checkbox
// 							id="favorites"
// 							label="Favorites"
// 							value={onlyFavorites}
// 							onChange={setOnlyFavorites}
// 						/>
// 						<Flex>
// 							<IconButton
// 								ariaLabel="Change folder filter"
// 								iconId="folder"
// 								onClick={openFolderFilterMenu}
// 							/>
// 							<IconButton
// 								ariaLabel="Change timestamp filter"
// 								iconId="clock"
// 								onClick={openListFilterMenu}
// 							/>
// 							<IconButton
// 								ariaLabel="Change properties filter"
// 								iconId="sliders-horizontal"
// 								onClick={openPropertiesFilterModal}
// 							/>
// 							<IconButton
// 								ariaLabel="Change sort order"
// 								iconId="arrow-up-narrow-wide"
// 								onClick={openSortMenu}
// 							/>
// 						</Flex>
// 					</Stack>
// 					<div>
// 						Showing {renderData.length} out of {folderFiles.length}
// 					</div>
// 				</Flex>
// 				<Stack spacing="sm">
// 					<TabList>
// 						<Tab onClick={() => setCurrentView("grid")}>Grid</Tab>
// 						<Tab onClick={() => setCurrentView("list")}>List</Tab>
// 					</TabList>
// 				</Stack>
// 			</div>
// 			{currentView === "grid" && <GridView data={renderData} />}
// 			{currentView === "list" && <ListView data={renderData} />}
// 		</div>
// 	);
// }
