// src/svelte/shared/components/property.svelte
<script lang="ts">
	import VaultExplorerPlugin from "src/main";
	import store from "../app/store";

	export let name: string;
	export let value: string;

	let plugin: VaultExplorerPlugin;
	store.plugin.subscribe((p) => {
		plugin = p;
	});

	function handleClick() {
		const searchPlugin = (plugin.app as any).internalPlugins.plugins[
			"global-search"
		];
		if (searchPlugin) {
			searchPlugin.instance.openGlobalSearch(`["${name}":${value}`);
		}
	}
</script>

<a
	href="none"
	class="tag vault-explorer-property"
	target="_blank"
	rel="noopener"
	on:click={handleClick}
>
	{value}
</a>

<style>
	.vault-explorer-property {
		background-color: var(--color-base-20) !important;
		color: var(--text-normal) !important;
		width: max-content;
		text-wrap: nowrap;
	}

	.vault-explorer-property:hover {
		background-color: var(--color-base-30) !important;
	}
</style>

// src/react/property/index.tsx
import { useAppMount } from "../AppMountProvider";
import "./styles.css";

interface Props {
	name: string;
	value: string;
}

export default function Property({ name, value }: Props) {
	const { app } = useAppMount();

	function handleClick() {
		const searchPlugin = (app as any).internalPlugins.plugins[
			"global-search"
		];
		if (searchPlugin) {
			searchPlugin.instance.openGlobalSearch(`["${name}":${value}`);
		}
	}

	return (
		<a
			// href={`["${source}"]`}
			className="tag frontmatter-view-property"
			target="_blank"
			rel="noopener"
			onClick={handleClick}
		>
			{value}
		</a>
	);
}
