// src/react/components/properties-filter-app/group-tag-list/index.tsx
import "./styles.css";

import Stack from "src/react/components/shared/stack";
import { PropertyFilterGroup } from "src/types";
import GroupTag from "../group-tag";

interface Props {
	groups: PropertyFilterGroup[];
	selectedGroupId: string;
	onGroupClick: (groupId: string) => void;
}

export default function GroupTagList({
	groups,
	selectedGroupId,
	onGroupClick,
}: Props) {
	return (
		<div className="vault-explorer-group-tag-list">
			<Stack>
				{groups.map((group, i) => {
					const { id, name } = group;
					const isSelected =
						selectedGroupId === ""
							? i === 0
							: id === selectedGroupId;
					return (
						<GroupTag
							key={id}
							name={name}
							isSelected={isSelected}
							onClick={() => onGroupClick(id)}
						/>
					);
				})}
			</Stack>
		</div>
	);
}

// src/svelte/properties-filter-app/components/group-tag-list.svelte
<script lang="ts">
	import { PropertyFilterGroup } from "src/types";
	import GroupTag from "./group-tag.svelte";
	import Stack from "src/svelte/shared/components/stack.svelte";

	export let groups: PropertyFilterGroup[] = [];
	export let selectedGroupId: string | undefined;
</script>

<div class="vault-explorer-group-tag-list">
	<Stack>
		{#each groups as group, index (group.id)}
			<GroupTag
				id={group.id}
				name={group.name}
				isSelected={selectedGroupId === undefined
					? index === 0
					: group.id === selectedGroupId}
				on:groupClick
			/>
		{/each}
	</Stack>
</div>

<style>
	.vault-explorer-group-tag-list {
		max-width: calc(100% - 50px);
		overflow-x: auto;
	}

	.vault-explorer-group-tag-list::-webkit-scrollbar {
		display: none;
	}
</style>
