// src/react/components/properties-filter-app/group-edit-view/index.tsx
import {
	PropertyFilterGroup,
	TextFilterCondition,
	TextPropertyFilter,
} from "src/types";
import IconButton from "../../shared/icon-button";
import Stack from "../../shared/stack";
import Divider from "../../shared/divider";
import PropertyFilterList from "../property-filter-list";
import { generateUUID } from "src/react/services/uuid";

interface Props {
	selectedGroup: PropertyFilterGroup;
	onBackClick: () => void;
	onGroupsChange: React.Dispatch<React.SetStateAction<PropertyFilterGroup[]>>;
}

export default function GroupEditView({
	selectedGroup,
	onBackClick,
	onGroupsChange,
}: Props) {
	function handleAddPropertyClick() {
		const newFilter: TextPropertyFilter = {
			id: generateUUID(),
			propertyName: "",
			operator: "and",
			isEnabled: true,
			condition: TextFilterCondition.IS,
			value: "",
		};

		onGroupsChange((groups) =>
			groups.map((group) =>
				group.id === selectedGroup.id
					? { ...group, filters: [...group.filters, newFilter] }
					: group
			)
		);
	}

	function handleGroupNameChange(name: string) {
		onGroupsChange((groups) =>
			groups.map((group) =>
				group.id === selectedGroup.id ? { ...group, name } : group
			)
		);
	}

	return (
		<Stack direction="column" align="flex-start" spacing="sm">
			<Stack spacing="sm">
				<IconButton
					ariaLabel="Back"
					iconId="arrow-left"
					onClick={onBackClick}
				/>
				<input
					type="text"
					value={selectedGroup.name}
					onChange={(e) => handleGroupNameChange(e.target.value)}
				/>
			</Stack>
			<Divider />
			<PropertyFilterList
				selectedGroup={selectedGroup}
				onGroupsChange={onGroupsChange}
			/>
			<IconButton
				ariaLabel="Add filter"
				iconId="plus"
				onClick={handleAddPropertyClick}
			/>
		</Stack>
	);
}

// src/svelte/properties-filter-app/components/group-edit-view.svelte
<script lang="ts">
	import Divider from "src/svelte/shared/components/divider.svelte";
	import IconButton from "src/svelte/shared/components/icon-button.svelte";
	import Stack from "src/svelte/shared/components/stack.svelte";
	import { generateUUID } from "src/svelte/shared/services/uuid";

	import {
		PropertyFilterGroup,
		TextFilterCondition,
		TextPropertyFilter,
	} from "src/types";
	import PropertyFilterList from "./property-filter-list.svelte";

	import { createEventDispatcher } from "svelte";
	import { createPropertyFilter } from "../utils";
	const dispatch = createEventDispatcher();

	export let selectedGroup: PropertyFilterGroup;

	function handleAddFilterClick() {
		const newFilter = createPropertyFilter();
		dispatch("filterAddClick", { filter: newFilter });
	}

	function handleGroupNameChange(e: Event) {
		const name = (e.target as HTMLInputElement).value;
		dispatch("groupNameChange", { name });
	}

	function handleBackClick() {
		dispatch("backClick");
	}
</script>

<Stack direction="column" align="flex-start" spacing="sm">
	<Stack spacing="sm">
		<IconButton
			ariaLabel="Back"
			iconId="arrow-left"
			on:click={handleBackClick}
		/>
		<input
			type="text"
			value={selectedGroup.name}
			on:change={handleGroupNameChange}
		/>
	</Stack>
	<Divider />
	{#if selectedGroup.filters.length > 0}
		<PropertyFilterList
			filters={selectedGroup.filters}
			on:groupClick
			on:filterConditionChange
			on:filterTypeChange
			on:filterNameChange
			on:filterValueChange
			on:filterToggle
			on:filterDeleteClick
		/>
	{/if}
	<IconButton
		ariaLabel="Add filter"
		iconId="plus"
		on:click={handleAddFilterClick}
	/>
</Stack>
