// src/react/components/properties-filter-app/property-filter-list/index.tsx
import { PropertyFilterGroup } from "src/types";
import Stack from "../../shared/stack";
import PropertyFilter from "../property-filter";

interface Props {
	selectedGroup: PropertyFilterGroup;
	onGroupsChange: React.Dispatch<React.SetStateAction<PropertyFilterGroup[]>>;
}

export default function PropertyFilterList({
	selectedGroup,
	onGroupsChange,
}: Props) {
	return (
		<Stack direction="column" spacing="md" width="100%">
			{selectedGroup.filters.map((filter) => {
				const { id, isEnabled, propertyName, condition, value } =
					filter;
				return (
					<PropertyFilter
						key={id}
						id={id}
						value={value}
						condition={condition}
						propertyName={propertyName}
						isEnabled={isEnabled}
						onGroupsChange={onGroupsChange}
					/>
				);
			})}
		</Stack>
	);
}

// src/svelte/properties-filter-app/components/property-filter-list.svelte
<script lang="ts">
	import Stack from "src/svelte/shared/components/stack.svelte";
	import PropertyFilter from "./property-filter.svelte";
	import { PropertyFilter as PropertyFilterType } from "src/types";

	export let filters: PropertyFilterType[] = [];
</script>

<Stack direction="column" spacing="md" width="100%">
	{#each filters as filter (filter.id)}
		<PropertyFilter
			id={filter.id}
			value={filter.value}
			condition={filter.condition}
			propertyName={filter.propertyName}
			isEnabled={filter.isEnabled}
			on:groupChange
			on:filterConditionChange
			on:filterNameChange
			on:filterValueChange
			on:filterToggle
			on:filterDeleteClick
		/>
	{/each}
</Stack>
