// src/react/grid-view/index.tsx
import Card from "../card";

import { MarkdownFileData } from "../types";

import "./styles.css";

interface Props {
	data: MarkdownFileData[];
}

export default function GridView({ data }: Props) {
	return (
		<div className="vault-explorer-grid-view">
			{data.map((file) => {
				const { name, tags, path, url, source, revision, status } =
					file;
				return (
					<Card
						key={path}
						name={name}
						path={path}
						url={url}
						tags={tags}
						source={source}
						revision={revision}
						status={status}
					/>
				);
			})}
			{/* <Virtuoso
					style={{ height: 400 }}
					data={data}
					itemContent={(index, file) => <Card name={file} />}
				/> */}
		</div>
	);
}

// src/svelte/app/components/grid-view.svelte
<script lang="ts">
	import { MarkdownFileRenderData } from "../types";
	import GridCard from "./grid-card.svelte";

	export let data: MarkdownFileRenderData[];
</script>

<div class="vault-explorer-grid-view">
	{#each data as file}
		<GridCard
			name={file.name}
			path={file.path}
			url={file.url}
			tags={file.tags}
			source={file.source}
			status={file.status}
		/>
	{/each}
</div>

<style>
	.vault-explorer-grid-view {
		display: grid;
		row-gap: 2rem;
		column-gap: 2rem;
		grid-template-columns: repeat(auto-fit, minmax(200px, 300px));
	}
</style>
