// src/react/components/app/list-view/index.tsx
import ListItem from "../list-item";

import { MarkdownFileRenderData } from "../types";

import "./styles.css";

interface Props {
	data: MarkdownFileRenderData[];
}

export default function ListView({ data }: Props) {
	return (
		<div className="vault-explorer-list-view">
			{data.map((file) => {
				const { name, path } = file;
				return <ListItem key={path} name={name} path={path} />;
			})}
			{/* <Virtuoso
					style={{ height: 400 }}
					data={data}
					itemContent={(index, file) => <Card name={file} />}
				/> */}
		</div>
	);
}

// src/svelte/app/components/list-view.svelte
<script lang="ts">
	import ListItem from "./list-item.svelte";

	import { MarkdownFileRenderData } from "../types";

	export let data: MarkdownFileRenderData[];
	export let startIndex: number;
	export let pageLength: number;

	let displayedItems: MarkdownFileRenderData[] = [];

	$: {
		if (startIndex < data.length) {
			displayedItems = Array.from({ length: pageLength }, (_, i) => {
				const index = startIndex + i;
				return data[index];
			});
		} else {
			displayedItems = [];
		}
	}
	//TODO replace file.path with a unique id that is generated when the file is added
</script>

<div class="vault-explorer-list-view">
	{#each displayedItems as file (file.path)}
		<ListItem name={file.name} path={file.path} />
	{/each}
</div>
